config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get '/whispaw', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  devise_for :users, path: "mon_compte"
  resource :users, :except => [:new, :create, :index, :destroy], path: "mon_profil"
  resources :tags, :except => [:edit, :update]
  resources :pets, path: "animaux" do
    resources :likes
    member do
      delete :delete_photo
    end
  end

  resources :messages
  resources :chatrooms, only: [:new, :create, :show, :index], path: "mes_conversations"
  mount ActionCable.server => '/cable'
end

app/models/pet.rb
class Pet < ApplicationRecord
  after_create :new_pet_send
  after_create :default_pet
  before_destroy :reset_default_pet

  belongs_to :user
  has_many :likes_as_liker, foreign_key: "liker", class_name: "Like", dependent: :destroy
  has_many :likes_as_liked, foreign_key: "liked", class_name: "Like", dependent: :destroy
  has_many_attached :photos, dependent: :destroy
  has_many :tag_pets, dependent: :destroy
  has_many :tags, through: :tag_pets
  validates :name, presence: true
  validates :birthdate, presence: true
  validates :animal, presence: true
  enum animal: [ :chat, :chien ]
  accepts_nested_attributes_for :tags
  CATBREED=['Manx','Birman','Persan','Siamois','Somali','Sibérien','Ragdoll', "Sphinx", "Européen","Autre"].sort
  DOGBREED=['Terrier','Dalmatien','Boxer','Berger Allemand','Labrador','Bouledogue','Chihuahua','Beagle','Setter','Cocker','Husky','Teckel', "Autre"].sort
  DISTANCEOTHERS=['< 5km','< 20km', '< 100km']

  def age
    return (Date.today - self.birthdate).to_i / 365
  end

  def self.search(search)
    if search
      search_list = search.downcase.split(" ")
      list_compare = Pet.all
      search_list.each do |value|
        tag = Tag.find_by(value: value)
        if value == "chat" || value == "chien"
          list = Pet.where(animal: value)
        elsif value == "femelle" || value == "mâle"
          list = Pet.where(sex: value.capitalize)
        elsif value.to_f > 0 || value == "0"
          list = Pet.where(birthdate: (Date.today - (value.to_i + 1).to_i.years)..(Date.today - value.to_i.years))
        elsif !tag.nil?
          list = tag.pets
        else
          list = Pet.all
        end
        list_compare = list & list_compare
      end
      return list_compare
    else
      return Pet.all
    end
  end
  
  def self.distance_to_others(distance_to_others, user)
    if distance_to_others == "< 5km"
      list = []
      User.near(user, 5, units: :km).each do |user|
        user.pets.each do |pet|
          list << pet
        end
      end
      return list
    elsif distance_to_others == "< 20km"
      list = []
      list = []
      User.near(user, 20, units: :km).each do |user|
        user.pets.each do |pet|
          list << pet
        end
      end
      return list
    elsif distance_to_others == "< 100km"
      list = []
      list = []
      User.near(user, 100, units: :km).each do |user|
        user.pets.each do |pet|
          list << pet
        end
      end
      return list
    else
      return Pet.all
    end
  end

  def new_pet_send
    UserMailer.new_pet_email(self).deliver_now
  end

  def short_description
    unless self.description.nil?
      short = self.description.split(" ").slice(0,13).join(" ")
      if short.last != "."
        short = short + " ..."
      end
      return short
    end
  end

  def default_pet
    my_user = self.user
    if my_user.default_pet_id.nil?
      current_pet = my_user.pets.last
      my_user.update(default_pet_id: current_pet.id)
    end
  end

  def reset_default_pet
    my_user = self.user
    if my_user.pets.size > 1
      last_other_pet = my_user.pets.where.not(id: self.id).last
      my_user.update(default_pet_id: last_other_pet.id)
    else
      my_user.update(default_pet_id: nil)
    end
  end

end

app/controllers/concerns/helpers/pets_helper.rb
module PetsHelper
  def current_pet?(pet)
    pet == Pet.find(current_user.default_pet_id)
  end

  def current_like(pet)
    current_pet = Pet.find(current_user.default_pet_id)
    return current_pet.likes_as_liker.where(liked_id: pet)
  end

  def liked?(pet)
    return Like.where(liker_id: @current_pet.id, liked_id: pet.id).exists?
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :edit, :destroy, :delete_photo]
  before_action :is_current_user?, only: [ :edit ]
  before_action :is_default_pet, only: [:index, :show]

  def index
    @current_pet = Pet.find(current_user.default_pet_id)
    @pets_list = Pet.search(params[:search]) & Pet.where.not(user_id: current_user.id) & Pet.distance_to_others(params[:distance_to_others], current_user)
    @your_user = current_user
  end

  def new
    @pet = Pet.new
    @tag = Tag.all
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    respond_to do |format|
      if @pet.save
        flash[:success] = "Le profil de l'animal a bien été créé."
        format.html { redirect_to pets_path }
        format.json { }
      else
        flash[:error] = "N'oubliez pas d'ajouter le nom et la date de naissance de votre animal !"
        format.html { render :new }
        format.json { }
      end
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @my_matches = Like.where(match: true, liker_id: current_user.default_pet_id)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: "Le profil de l'animal a bien été édité."}
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to users_path
  end

  def delete_photo
    @photo = ActiveStorage::Attachment.find(params[:id])
    respond_to do |format|
      if @photo.purge
        format.html { redirect_to request.referrer }
        format.json { }
      end
    end
  end

  def every_pet?(pets)
    return pets == Pet.where.not(user_id: current_user.id)
  end

  private
    def pet_params
      params.require(:pet).permit(:name, :animal, :breed, :sex, :age, :birthdate, :user, :description, :search, photos: [], tag_ids: [])
    end

    def is_current_user?
      if current_user != Pet.find(params[:id]).user
        flash[:error] = "Vous ne pouvez pas accéder au profil de cet animal."
        redirect_to root_path
      end
    end

    def is_default_pet
      if current_user.default_pet_id.nil?
        flash[:error] = "Vous devez d'abord créer un profil animal."
        redirect_to new_pet_path
      end
    end

end

app/views/pets/_bubbling_heart.html.erb
<div class="bubbling-heart">
  <div><i class="fa fa-heart fa-5x"></i></div>
  <div><i class="fa fa-heart fa-5x"></i></div>
  <div><i class="fa fa-heart fa-5x"></i></div>
  <div><i class="fa fa-heart fa-5x"></i></div>
  <div><i class="fa fa-heart fa-5x"></i></div>
  <div><i class="fa fa-heart fa-5x"></i></div>
</div>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :animal %>
    <%= form.text_field :animal %>
  </div>
  <div class="field">
    <%= form.label :chip_number %>
    <%= form.text_field :chip_number %>
  </div>
  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>
  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>
  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_index.html.erb
<div class="small-jumbotron text-center ">
</div>
<!-- Search bar will be here, need to implement post-MVP -->
<div class="container text-center">
  <%= link_to "Trouver des Animaux", pets_path, class:"btn btn-large btn-primary"  %>
</div>

app/views/pets/delete_photo.js.erb
document.getElementById("photo<%= @photo.id %>").remove()

app/views/pets/edit.html.erb
<div class="container mb-5">
  <div class="font-weight-bold mt-5 mb-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", pets_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Mon profil", users_path, class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to @pet.name, pet_path(@pet.id), class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Éditer son profil", edit_pet_path(@pet), class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="mt-5 col-md-6 offset-md-3 shadow p-3 mb-5 rounded bg-devise container-pet shadow text-center">
    <i class="fa fa-paw mt-2 fa-5x"></i>
    <h3 class="mt-3 mb-5">Édite ton ami à quatre pattes</h3>
    <div class="text-center my-2">
      <%= form_for @pet, :url => pet_path(@pet.id), method: :patch, multipart: true do |f| %>
        <h6 class="card-text mt-2">Nom :</h6>
        <div class="input-group mb-4">
          <%= f.text_field :name, autofocus: true, placeholder: @pet.name, class:"form-control" %>
        </div>
        <h6 class="card-text mt-2">Date de naissance :</h6>
        <div class="input-group mb-4">
          <%= f.date_field :birthdate, max: Date.today, autofocus: true, placeholder: @pet.birthdate, class:"form-control" %>
        </div>
        <h6 class="card-text mt-2">Race :</h6>
        <div class="input-group mb-4">
          <%if @pet.chat? %>
            <%= f.select :breed, options_for_select(Pet::CATBREED), include_blank: @pet.breed, autofocus: true, class:"form-control" %>
          <% elsif @pet.chien? %>
           <%= f.select :breed, options_for_select(Pet::DOGBREED), include_blank: @pet.breed, autofocus: true, class:"form-control" %>
          <% end %>
        </div>
        <h6 class="card-text mt-2">Tags :</h6>
        <div class="input-group mb-4">
          <%= f.select :tag_ids, Tag.all.collect {|p| [ p.value, p.id ]}, {}, include_blank: true, multiple: true, class:"form-control"%>
        </div>
        <h6 class="card-text mt-2">En quelques mots :</h6>
        <div class="input-group mb-4">
          <%= f.text_field :description, autofocus: true, placeholder: @pet.description, class:"form-control" %>
        </div>
        <h6 class="card-text mb-2">Photos actuelles :</h6>
        <div class="input-group mb-4 input-checkbox">
          <% if @pet.photos.attached? %>
            <% @pet.photos.each do |p| %>
              <% id = "photo" + p.id.to_s %>
              <%= image_tag p, class: "img-pet-new-edit form-border thick-lined mb-2", id: id %>
              <div class="maintext">
                <%= link_to delete_photo_pet_url(p.id), method: :delete, remote: true do %><i class="trash-icon fa fa-trash"></i><% end %>
              </div>
            <% end %>
          <% else %>
            <p>Pas de photos encore</p>
          <% end %>
        </div>
        <h6 class="card-text">Ajouter des photos :</h6>
        <div class="input-group mb-4 input-checkbox">
          <label class="file-input">
            <%= f.file_field :photos, multiple: true, value: "", class: "uploadPreview ml-5 mt-0 mb-2 preview-button" %>
          </label>
        </div>
        <div id="showPreview"></div>
          <div class="actions my-3">
            <%= f.submit "Éditer le profil", class:"btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="text-center ">
  <%=image_tag("doggo_home.jpg", class: "small-jumbotron", alt: "")%>
</div>
<div class="container">
  <a tabindex="0" class="btn btn-outline-primary btn-info-match" role="button" data-html="true" data-toggle="popover" data-trigger="focus" title="C'est quoi un match ?" data-content="Rien n'est plus simple : si un animal vous plaît, cliquez sur le cœur sur son profil. <br>Lorsque cet animal like aussi votre profil, c'est un Match !"> Match ? </a>
  <a tabindex="0" class="btn btn-outline-secondary btn-info-match mx-3" role="button" data-html="true" data-toggle="popover" data-trigger="focus" title="Comment chercher de nouveaux amis ?" data-content="Dans la barre de recherche ajoutez les critères que vous recherchez chez vos <i>amimaux</i>. Séparez chaque critère par un espace. <br>Vous pouvez filtrer les résultats selon l'âge, le sexe, l'espèce et les tags attribués à chaque profil. <br>Vous pouvez également rechercher les profils selon leur proximité géographique. <br><strong>Exemple : 'chien femelle 4 ans doux calme actif. Distance : < 20km'.</strong>"> Recherche ? </a>
  <h4 class="mb-4">Rechercher par espèce, âge, sexe ou tags... et proximité</h4>
  <!-- Search bar -->
  <div class="form-inline form-inline-search my-4 mb-5">
    <%= form_tag(pets_path, method: :get, class:"form-group form-control alert-light") do%>
      <%= text_field_tag(:search, params[:search], class:"form-control col-sm-8 col-xs-8", placeholder: "tags, age, espèce, sexe...")%>
      <%= hidden_field_tag :user_id , @current_user.id %>
      <%= select_tag :distance_to_others, options_for_select(Pet::DISTANCEOTHERS), prompt: "Distance", class:"form-control col-sm-2 col-xs-2" %>
      <%= submit_tag "Rechercher", class:"btn btn-outline-primary btn-main-page" %>
    <% end %>
  </div>
</div>
<div class="container justify-content-around">
  <div class="row justify-content-around ml-2 mr-2">
    <% @pets_list.each do |pet| %>
      <% unless liked?(pet)%>
        <div class="col-sm-4">
          <div id="likeCard<%= pet.id %>" class="card bg-light mb-4">
            <div id="likeHeader<%= pet.id %>" class="card-header">
              <% name = pet.name%>
              <%= link_to name, pet_path(pet.id), class: "h4 card-title float-left pet-card-title" %>
              <% pet.tags.each do |tag|%>
                <span class='badge badge-secondary mr-2 mb-1 float-right'><%=tag.value%></span>
              <%end%>
            </div>
            <div id="likeBody<%= pet.id %>" class="card-body">
              <!---------------------IMAGE CAROUSEL--------------------->
              <div id="demo" class="carousel slide" data-ride="carousel" data-interval="7000">
                <div class="carousel-inner" >
                  <% unless pet.photos.empty? %>
                    <div class="carousel-item active">
                      <%= image_tag pet.photos.first, class: "custom-img-size" %>
                    </div>
                    <% pet.photos[1..-1].each do |p| %>
                      <div class="carousel-item">
                        <%= image_tag p, class: "custom-img-size" %>
                      </div>
                    <% end %>
                  <% else %>
                    <div class="carousel-item active">
                      <%= image_tag("paw.svg", {class: "custom-img-size"} ) %>
                    </div>
                    <div class="carousel-item">
                      <%= image_tag("paw.svg", {class: "custom-img-size"} ) %>
                    </div>
                  <%end%>
                </div>
              </div>
              <!---------------------CARD BODY END--------------------->
              <div class="mt-3">
                <% if pet.short_description != nil %>
                  <h6 class="card-subtitle my-3 text-primary text-truncate"><em>"<%= pet.short_description%>"</em></h6>
                <% end %>
                <h6 class="card-subtitle mt-2 float-left">
                  <%= pet.animal.capitalize %>,
                  <% if pet.birthdate != nil %>
                    <% if pet.age > 1 %>
                      <%= pet.age %> ans,
                    <% else %>
                      <%= pet.age %> an,
                    <% end %>
                  <% end %>
                  <%= pet.sex %>
                </h6>
                <%= link_to pet_likes_path(pet.id), method: :post, remote: true do %>
                  <i id="likeButton<%= pet.id %>" class="btn btn-outline-primary btn-sm fa fa-heart float-right"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
  <div class="container font-weight-bold m-5">
    <%= link_to "Retour", :back %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container mb-5">
  <div class="font-weight-bold mt-5 mb-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", pets_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Mon profil", users_path, class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Créer le profil de mon animal", new_pet_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="mt-5 col-md-6 offset-md-3 shadow p-3 mb-5 rounded bg-devise container-pet shadow text-center">
    <i class="fa fa-paw mt-2 fa-5x"></i>
    <h3 class="mt-3 ">Ajoute ton bourreau des cœurs à quatre pattes</h3>
    <p class="text-red mb-5">* champs obligatoires</p>
    <div class="text-center my-2" >
      <%= form_for @pet, :url => pets_path, multipart: true do |f| %>
        <h6 class="card-text mt-2">Nom :<span class="text-red"> *</span></h6>
        <div class="input-group mb-4">
          <%= f.text_field :name, autofocus: true, class:"form-control" %>
        </div>
        <h6 class="card-text mt-2">Genre :<span class="text-red"> *</span></h6>
        <div class="input-group mb-4 input-checkbox">
          <label class="form-control mr-0 pet-radio-button">
            <%= f.radio_button :sex, 'Femelle', class:"radio-button", type: "radio", checked: true %><span class="">Femelle</span>
          </label>
          <label class="form-control ml-0 border-left-0 pet-radio-button">
            <%= f.radio_button :sex, 'Mâle', class:"radio-button", type: "radio" %><span class="">Mâle</span>
          </label>
        </div>
        <h6 class="card-text mt-2">Espèce :<span class="text-red"> *</span></h6>
        <div class="input-group mb-4 input-checkbox">
          <label class="form-control mr-0 pet-radio-button">
            <%= f.radio_button :animal, 'chien', class:"radio-button", id: "pet-radio", type: "radio", checked: true %><span class="">Chien</span>
          </label>
          <label class="form-control ml-0 border-left-0 pet-radio-button">
            <%= f.radio_button :animal, 'chat', class:"radio-button", id: "pet-radio", type: "radio" %><span>Chat</span>
          </label>
        </div>
        <h6 class="card-text mt-2">Date de naissance :<span class="text-red"> *</span></h6>
        <div class="input-group mb-3">
          <%= f.date_field :birthdate, max: Date.today, autofocus: true, class:"form-control p-2"%>
        </div>
        <h6 class="card-text mt-2">Tags :</h6>
        <div class="input-group mb-4">
          <%= f.select :tag_ids, Tag.all.collect {|p| [ p.value, p.id ]}, {}, type: "select", include_blank: true, multiple: true, class:"form-control" %>
        </div>
        <h6 class="card-text mt-2">En quelques mots :</h6>
        <div class="input-group mb-4">
          <%= f.text_area :description, autofocus: true, rows: 1, class:"form-control" %>
        </div>
        <p class="card-text mb-0">Mise en ligne le : <%= Time.now.strftime("%d/%m/%Y") %> </p><br>
        <h6 class="card-text">Photos :</h6>
        <div class="input-group mb-4 input-checkbox">
          <label class="file-input">
            <%= f.file_field :photos, multiple: true, value: "", class: "uploadPreview ml-5 mt-0 mb-2 preview-button" %>
          </label>
        </div>
        <div id="showPreview"></div>
        <div class="actions my-3">
          <%= f.submit "Créer le profil", class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/search.js.erb
// Filter anything

// Query for 2nd barr

$('.dropdown').each(function(index, dropdown){

//Find the input search box
let search = $(dropdown).find('.search');

//Find every item inside the dropdown
let items = $(dropdown).find('.dropdown-item');

//Capture the event when user types into the search box
$(search).on('input', function(){
    filter($(search).val().trim().toLowerCase())
});

//For every word entered by the user, check if the symbol starts with that word
//If it does show the symbol, else hide it
function filter(word) {
    let length = items.length
    let collection = []
    let hidden = 0
    for (let i = 0; i < length; i++) {
        if (items[i].value.toLowerCase().includes(word)) {
            $(items[i]).show()
        }
        else {
            $(items[i]).hide()
            hidden++
        }
    }

    //If all items are hidden, show the empty view
    if (hidden === length) {
        $(dropdown).find('.dropdown_empty').show();
    }
    else {            
        $(dropdown).find('.dropdown_empty').hide();
    }
}

//If the user clicks on any item, set the title of the button as the text of the item
$(dropdown).find('.dropdown-menu').find('.menuItems').on('click', '.dropdown-item', function(){
    $(dropdown).find('.dropdown-toggle').text($(this)[0].value);
    $(dropdown).find('.dropdown-toggle').dropdown('toggle');
})
});

app/views/pets/show.html.erb
<div class="container mb-5">
  <div class="font-weight-bold mt-5 mb-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", pets_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
      <% if current_user == @pet.user %>
        <li class="breadcrumb-item">
          <%= link_to "Mon profil", users_path, class:"item-breadcrumb" %>
        </li>
      <% elsif @my_matches.where(liked_id: @pet.id).exists? %>
        <li class="breadcrumb-item">
          <%= link_to "Mes matchs", pet_likes_path(current_user.default_pet_id), class:"item-breadcrumb" %>
        </li>
      <% end %>
      <li class="breadcrumb-item">
        <%= link_to @pet.name, pet_path(@pet.id), class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="mt-5 col-md-6 offset-md-3 shadow p-3 mb-5 rounded bg-devise container-pet shadow container-pet-show text-center">
    <div id="demo" class="carousel slide" data-ride="carousel" data-interval="7000">
      <div class="carousel-inner" >
        <% unless @pet.photos.empty? %>
          <div class="carousel-item active">
            <%= image_tag @pet.photos.first, class: "avatar avatar-xlg mb-3 rounded-circle" %>
          </div>
          <% @pet.photos[1..-1].each do |p| %>
            <div class="carousel-item">
              <%= image_tag p, class: "avatar avatar-xlg mb-3 rounded-circle" %>
            </div>
          <% end %>
        <% else %>
          <%= image_tag "michat.jpg", class: "avatar avatar-xlg mb-3 rounded-circle"  %>
        <%end%>
      </div>
    </div>
    <h4><%= @pet.name %> · <%= @pet.animal %></h4>
    <p><strong>Race :</strong> <%= @pet.breed %></p>
    <p><strong>Genre :</strong> <%= @pet.sex %></p>
    <p><strong>Date de naissance :</strong> <%= @pet.birthdate.strftime("%d/%m/%Y") %></p>
      <% if @pet.age > 1 %>
        <p><strong>Âge :</strong> <%= @pet.age %> ans</p>
      <% else %>
        <p><strong>Âge :</strong> <%= @pet.age %> an</p>
      <% end %>
    <p><strong>À propos :</strong> <%= @pet.description %></p>
    <p><strong>Tags :</strong>
      <% @pet.tags.each do |tag|%>
        <span class='badge badge-secondary mr-2 mb-1'><%=tag.value%></span>
      <%end%>
    </p>
    <div class="btns-pet-show">
      <%if current_user == @pet.user%>
        <%= link_to 'Editer son profil', edit_pet_path(@pet), "data-turbolinks" => "false", class: "btn btn-primary btn-edit-pet-profile" %>
        <%= link_to 'Supprimer', pet_path(@pet), data: { confirm: "Etes-vous certain(e)?" }, method: :delete, class: "btn btn-outline-primary" %>
      <%end%>
    </div>
  </div>
</div>