config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get '/whispaw', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  devise_for :users, path: "mon_compte"
  resource :users, :except => [:new, :create, :index, :destroy], path: "mon_profil"
  resources :tags, :except => [:edit, :update]
  resources :pets, path: "animaux" do
    resources :likes
    member do
      delete :delete_photo
    end
  end

  resources :messages
  resources :chatrooms, only: [:new, :create, :show, :index], path: "mes_conversations"
  mount ActionCable.server => '/cable'
end

app/models/like.rb
class Like < ApplicationRecord
  after_commit :new_match_user1, on: :create
  after_commit :new_match_user2, on: :create
  after_create :match_pet
  before_destroy :unmatch, on: :destroy
  belongs_to :liker, class_name: "Pet"
  belongs_to :liked, class_name: "Pet"
  validates :liked, uniqueness: { scope: [:liker]}
  validate :different_pets

  def different_pets
    if self.liked == self.liker
      errors.add(:liked, 'Narcissisme!')
      errors.add(:liker, 'Narcissisme!')
    end
  end

  def new_match_user1
    if already_liked?
      UserMailer.new_match_email1(self).deliver_now
    end
  end

  def new_match_user2
    if already_liked?
      UserMailer.new_match_email2(self).deliver_now
    end
  end

  def current_pet
    current_pet = Pet.find(current_user.default_pet_id)
  end

  def already_liked?
    liker_pet = Pet.find(self.liked_id)
    liked_pet = Pet.find(self.liker_id)
    return Like.where(liked_id: liked_pet.id, liker_id: liker_pet.id).exists?
  end

  def match_pet
    if already_liked? == true
      self.update(match: true)
      match_back = Like.where(liker_id: self.liked_id,liked_id: self.liker_id)
      match_back.first.update(match: true)
    else
      self.match = false
    end
  end

  def unmatch
    if self.match == true
      unmatched = Like.where(liker_id: self.liked_id,liked_id: self.liker_id)
      unmatched.first.update(match: false)
    end
  end

end

app/controllers/concerns/helpers/likes_helper.rb
module LikesHelper
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :current_pet, only: [:create,:update,:destroy]

  def index
    @my_likes = Like.where(match: false,liker_id: current_pet.id)
    @my_search = get_pets(@my_likes) & Pet.search(params[:search]) & Pet.where.not(user_id: current_user.id)
    @my_matches = Like.where(match: true,liker_id: current_pet.id)
  end

  def show
    @my_likes = Like.where(match: false,liker_id: current_pet.id)
    @my_matches = Like.where(match: true,liker_id: current_pet.id)
  end

  def new
    @like = Like.new
  end

  def create
    @pet = Pet.find(params['pet_id'])
    @like = Like.new(liker_id: current_pet.id, liked_id: @pet.id)
    respond_to do |format|
      if @like.save!   
        if already_liked?(@like)
          chatroom_match!(@like, @pet)
        end
        format.html { redirect_to pets_path, notice: "J'adore!" }
        format.js { }
      end
    end
  end

  def destroy
    @pet = Pet.find(params['pet_id'])
    @like = Like.find(params['id'])
    @like.destroy!
    respond_to do |format|
      format.html { redirect_to pets_path, error: "Like supprimé." }
      format.js { }
    end
  end

  def current_pet
    return current_pet = Pet.find(current_user.default_pet_id)
  end

  def already_liked?(like)
    liker_pet = Pet.find(like.liked_id)
    liked_pet = Pet.find(like.liker_id)
    return Like.where(liked_id: liked_pet.id, liker_id: liker_pet.id).exists?
  end

  def chatroom_match!(like, pet)
    @title = "#{Pet.find(like.liked_id).name} et #{Pet.find(like.liker_id).name}"
    @chatroom = Chatroom.new
    @chatroom = current_user.chatrooms.build(title: @title)
    @chatroom.users << current_user
    @chatroom.users << pet.user
    @chatroom.save
  end

  def get_pets(likes)
    search_likes = []
    likes.each do |like|
      search_likes << Pet.find(like.liked_id)
    end
    return search_likes
  end

end

app/views/likes/_match.html.erb
<span class="badge badge-warning float-right">C'est un match</span>

app/views/likes/_userinfo.html.erb
<h6 class="float-left">C'est l'animal de <%= pet.user.first_name%>. Ecris-lui!<br>
Voici son e-mail <b><%= pet.user.email%></b></h6>

app/views/likes/create.js.erb
document.getElementById("likeCard<%= @pet.id %>").classList.add("wiggle")
document.getElementById("likeButton<%= @pet.id %>").classList.replace("btn-outline-primary","btn-primary")

app/views/likes/destroy.js.erb
document.getElementById("likeCard<%= @pet.id %>").classList.add("wiggle")
document.getElementById("dislikeButton<%= @pet.id %>").classList.replace("btn-primary","btn-outline-dark")

app/views/likes/index.html.erb
<div class="text-center ">
  <%=image_tag("doggo_home.jpg", class: "small-jumbotron", alt: "")%>
</div>
<div class="container">
  <div class="font-weight-bold mb-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", pets_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Mes matches et likes", pet_likes_path(current_user.default_pet_id), class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="text-center">
    <% if @my_matches.empty? %>
      <h2>Mes Matchs</h2>
      <div class="text-center mt-5 text-match">
        <h4>Oh you can't hurry love, oh you just have to wait...</h4>
        <h6>On n'est pas totalement d'accord<br>
          Le monde est plein <span class="animal-friend">d'amimaux</span>,
          <%=link_to pets_path, class:"go-like" do%>
            va les liker<i class="fa fa-paw ml-1"></i>
          <%end%>
        </h6>
      </div>
    <% else %>
      <h2>Mes Matchs <small><em> ...les petits chanceux !</em></small></h2>
      <div class="row justify-content-around ml-2 mr-2 mt-5 mb-5">
        <% @my_matches.each do |like| %>
          <div class="col-sm-4">
            <div id="likeCard<%= like.liked_id %>" class="card bg-custom text-white mb-4">
              <div id="likeHeader<%= like.liked_id %>" class="card-header">
                <% name = like.liked.name%>
                <%= link_to name, pet_path(like.liked_id), class: "h4 card-title float-left text-light pet-card-title" %>
                <span class="badge badge-warning float-right mr-2">C'est un match</span><br>
                <% like.liked.tags.each do |tag|%>
                  <span class='badge badge-secondary mr-2 mb-1 float-right'><%=tag.value%></span>
                <%end%>
              </div>
              <div id="likeBody<%= like.liked_id %>" class="card-body">
                <!---------------------IMAGE CAROUSEL--------------------->
                <div id="demo" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" >
                    <% unless like.liked.photos.empty? %>
                      <div class="carousel-item active">
                        <%= image_tag like.liked.photos.first, class: "custom-img-size" %>
                      </div>
                      <% like.liked.photos[1..-1].each do |p| %>
                        <div class="carousel-item">
                          <%= image_tag p, class: "custom-img-size" %>
                        </div>
                      <% end %>
                    <% else %>
                      <div class="carousel-item active">
                        <%= image_tag("paw.svg", {class: "custom-img-size"} ) %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <!---------------------CARD BODY END--------------------->
                <div class="mt-3">
                  <% if (like.liked.user.address.present? || like.liked.user.city.present? || like.liked.user.country.present?) && (current_user.address.present? || current_user.city.present? || current_user.country.present?) %>
                    <% if (like.liked.user.distance_to(current_user).to_i < 1) %>
                      <h6 class="card-subtitle my-3 text-white">À moins de 1 km</h6>
                    <% else %>
                      <h6 class="card-subtitle my-3 text-white">À <%= like.liked.user.distance_to(current_user).round %> km</h6>
                    <% end %>
                  <% else %>
                    <% if like.liked.short_description != nil %>
                      <h6 class="card-subtitle my-3 text-white text-truncate"><em>"<%= like.liked.short_description%>"</em></h6>
                    <% end %>
                  <% end %>
                  <h6 class="card-subtitle mt-2 float-left">
                    <%= like.liked.animal.capitalize %>,
                    <% if like.liked.birthdate != nil %>
                      <% if like.liked.age > 1 %>
                        <%= like.liked.age %> ans,
                      <% else %>
                        <%= like.liked.age %> an,
                      <% end %>
                    <% end %>
                    <%= like.liked.sex %>
                  </h6>
                  <h5 class="float-right">
                    <%=link_to "Écris-lui !", chatrooms_path, class:"btn btn-primary btn-sm mr-1" %>
                    <%= link_to pet_like_path(like.liked_id, like.id), method: :delete, remote: true do %>
                      <i id="dislikeButton<%= like.liked_id %>" class="btn btn-dark btn-sm fa fa-ban"></i>
                    <% end %>
                  </h5>
                </div>            
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="container text-center mb-5">
  <h2>Mes Likes</h2>
  <% if @my_likes.empty? %>
    <div class="text-center mt-5">
      <h4>Dépèche-toi, 
        <%=link_to pets_path, class:"go-like" do%>
          va liker les animaux les plus cools <i class="fa fa-paw"></i>
        <%end%>
      du web</h4>
    </div>

  <% else %>

    <!-- Responsive search bar-->
    <div class="d-flex justify-content-center h-100 my-4">
      <h5 class="mr-4 pt-3">Rechercher dans mes likes : </h5>
      <%= form_tag(pet_likes_path, method: :get, class:"searchbar") do%>
        <%= text_field_tag(:search, params[:search], class:"search_input", placeholder: "tags, age, espèce, sexe...")%>
        <%= button_tag(type: "submit", class: "search_icon") do %>
          <i class="fa fa-paw"></i>
        <% end %>
      <% end %>
    </div>
  
    <div class="row justify-content-around ml-2 mr-2 mt-4">
      <% @my_search.each do |pet| %>
        <div class="col-sm-4">
          <div id="likeCard<%= pet.id %>" class="card bg-light mb-4">
            <div id="likeHeader<%= pet.id %>" class="card-header">
              <% name = pet.name %>
              <%= link_to name, pet_path(pet.id), class: "h4 card-title float-left" %>
              <% pet.tags.each do |tag|%>
                <span class='badge badge-secondary mr-2 mb-1 float-right'><%=tag.value%></span>
              <%end%>
            </div>
            <div id="likeBody<%= pet.id %>" class="card-body">
              <div id="demo" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner" >
                  <% unless pet.photos.empty? %>
                    <div class="carousel-item active">
                      <%= image_tag pet.photos.first, class: "custom-img-size" %>
                    </div>
                    <% pet.photos[1..-1].each do |p| %>
                      <div class="carousel-item">
                        <%= image_tag p, class: "custom-img-size" %>
                      </div>
                    <%end%>
                  <% else %>
                    <div class="carousel-item active">
                      <%= image_tag("paw.svg", {class: "custom-img-size"} ) %>
                    </div>
                  <%end%>
                </div>
                <!---------------------CARD BODY END--------------------->
                <div class="mt-3">
                  <% if pet.short_description != nil %>
                    <h6 class="card-subtitle my-3 text-primary text-truncate"><em>"<%= pet.short_description%>"</em></h6>
                  <% end %>
                  <h6 class="card-subtitle mt-2 float-left">
                    <%= pet.animal.capitalize %>,
                    <% if pet.birthdate != nil %>
                      <% if pet.age > 1 %>
                        <%= pet.age %> ans,
                      <% else %>
                        <%= pet.age %> an,
                      <% end %>
                    <% end %>
                    <%= pet.sex %>
                  </h6>
                  <%= link_to pet_like_path(pet.id, pet.likes_as_liked.find_by(liker_id: current_pet).id), method: :delete, remote: true do %>
                    <i id="dislikeButton<%= pet.id %>" class="btn btn-primary btn-sm fa fa-ban float-right"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/likes/update.js.erb
document.getElementById("likeCard<%= @pet.id %>").classList.add("wiggle")
document.getElementById("likeCard<%= @pet.id %>").classList.replace("bg-light","bg-custom")
document.getElementById("likeCard<%= @pet.id %>").classList.add("text-white")
document.getElementById("likeCard<%= @pet.id %>").classList.add("scale-down")
document.getElementById("likeHeader<%= @pet.id %>").insertAdjacentHTML("beforeend","<%= j render 'match' %>")
document.getElementById("likeHeader<%= @pet.id %>").insertAdjacentHTML("beforeend","<%= j render 'userinfo', pet: @pet %>")