config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get '/whispaw', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  devise_for :users, path: "mon_compte"
  resource :users, :except => [:new, :create, :index, :destroy], path: "mon_profil"
  resources :tags, :except => [:edit, :update]
  resources :pets, path: "animaux" do
    resources :likes
    member do
      delete :delete_photo
    end
  end

  resources :messages
  resources :chatrooms, only: [:new, :create, :show, :index], path: "mes_conversations"
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :full_address 
  after_validation :geocode, if: ->(obj){ obj.full_address.present? and obj.full_address_changed? }

  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol
  /x

  after_create_commit :welcome_send

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password,
    presence: true,
    length: { in: Devise.password_length },
    format: { with: PASSWORD_FORMAT },
    confirmation: true,
    on: :create

  validates :password,
    allow_nil: true,
    length: { in: Devise.password_length },
    format: { with: PASSWORD_FORMAT },
    confirmation: true,
    on: :update

  validates :email,
    uniqueness: true

  has_many :pets, dependent: :destroy
  has_many :chatroom_users, dependent: :destroy
  has_many :chatrooms, through: :chatroom_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  def full_address
    [address, city, country].compact.join(', ')
  end  

  def full_address_changed?
    address_changed? || city_changed? || country_changed?
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def current_pet
    return Pet.find(self.default_pet_id)
  end

  def default_pet
    if self.pets.empty?
      return false
    elsif self.default_pet_id.nil?
      current_pet = self.pets.last
      self.default_pet_id.update(current_pet.id)
      return true
    else
      return true 
    end  
  end

  def name
    email.split('@')[0]
  end

end

app/controllers/concerns/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success]="Bravo ! Ton profil à correctement été mis à jour."
    else
      flash[:error]="Mince, il y a eu une erreur"
    end
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:id, :first_name, :last_name, :address, :city, :country, :default_pet_id)
    end
end

app/views/users/_show.html.erb
<div class="container">
  <div class="font-weight-bold mb-5 mt-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", root_path, class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Mon profil", users_path, class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="mt-5 text-center col shadow p-3 mb-5 bg-white rounded">
    <h2 class="mt-3 mb-5">Mon profil humain</h2>
    <div class="text-center my-2">
      <div class="row">
        <div class="col-12">
          <div class="text-center my-2">
            <div class="input-group info-user mb-3">
              <span class="input-group-text info-user"><i class="fa fa-envelope" aria-hidden="true" ></i></span>
              <span class="user-email ml-2"><h6 class="info-user-text"><%= @user.email%></h6></span>
            </div>
            <div class="actions my-3">
              <%= link_to "Éditer mon profil", edit_users_path, "data-turbolinks" => "false", class:"btn btn-primary" %>
              <%= link_to "Éditer mon log in", edit_user_registration_path, class:"btn btn-outline-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr/>
  <div class="mt-5 text-center col shadow p-3 mb-5 bg-white rounded">
    <h3 class="mt-3">Mes <span class="animal-friend">Amimaux</span></h3>
    <p class="mt-3">Vous n'avez aucun profil d'animal enregistré.</p>
    <div class="col md-6 text-center">
      <div class="actions my-3 mt-4">          
        <%= link_to "Créer un animal", new_pet_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="font-weight-bold mb-5 mt-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", pets_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Mon profil", users_path, class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Éditer mon profil", edit_users_path, class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="mt-5 col-md-6 offset-md-3 shadow p-3 mb-5 rounded bg-devise container-pet shadow text-center">
    <i class="fa fa-paw mt-2 fa-5x"></i>
    <h3 class="mt-3 mb-3">Éditer mon profil</h3>
    <a tabindex="0" class="btn btn btn-outline-primary btn-info-match" role="button" data-html="true" data-toggle="popover" data-trigger="focus" title="À quoi servent vos informations personnelles ?" data-content="Vos noms et prénoms seront donnés uniquement aux profils avec lesquels vous avez matchés, ce qui est plus personnel que de transmettre uniquement votre adresse email. <br>Quant à vos données géographiques, elles vous permettent de trouver des <i>amimaux</i> près de chez vous."> Pourquoi donner mes infos ? </a>
    <div class="text-center my-2">
      <%= form_for(current_user, url: users_path(current_user), method: :put) do |f| %>
        <div class="form-inline">
          <div class="col-6 col-first">
            <h6 class="card-text mt-2">Prénom :</h6>
            <div class="input-group mb-4">
              <%= f.text_field :first_name, placeholder: @user.first_name, class:"form-control" %>
            </div>
          </div>
          <div class="col-6 col-second">
            <h6 class="card-text mt-2">Nom :</h6>
            <div class="input-group mb-4">
              <%= f.text_field :last_name, placeholder: @user.last_name, class:"form-control" %>
            </div>
          </div>
        </div>
        <hr>
        <h6 class="card-text mt-4">Adresse :</h6>
        <div class="input-group mb-4">
          <%= f.text_field :address, placeholder: @user.address, class:"form-control" %>
        </div>
        <div class="form-inline">
          <div class="col-6 col-first">
            <h6 class="card-text mt-2">Ville :</h6>
            <div class="input-group mb-4">
              <%= f.text_field :city, placeholder: @user.city, class:"form-control" %>
            </div>
          </div>
          <div class="col-6 col-second">
            <h6 class="card-text mt-2">Pays :</h6>
            <div class="input-group mb-4">
              <%= f.text_field :country, placeholder: @user.country, class:"form-control" %>
            </div>
          </div>
        </div>
        <hr>
        <%if @user.default_pet_id != nil %> 
          <h6 class="card-text mt-4">Animal en vedette :</h6>
          <div class="input-group mb-5">
            <%= f.select :default_pet_id, current_user.pets.collect { |p| [ p.name, p.id ] }, include_blank: true, class:"form-control" %>
          </div>
        <% end %>
        <div class="actions">
          <%= f.submit "Mettre à jour", class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="mt-5">
      <%= link_to 'Ajouter un animal', new_pet_path %><br>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mb-5">
  <div class="font-weight-bold mb-5 mt-5">
    <ol class="breadcrumb-container">
      <li class="breadcrumb-item">
        <%= link_to "Accueil", pets_path, "data-turbolinks" => "false", class:"item-breadcrumb" %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Mon profil", users_path, class:"item-breadcrumb" %>
      </li>
    </ol>
  </div>
  <div class="mt-5 text-center col shadow p-3 mb-5 bg-white rounded">
    <h2 class="mt-3 mb-5">Mon profil humain</h2>
    <div class="text-center my-2">
      <div class="row">
        <div class="col-12">
          <div class="text-center my-2">
            <% if @user.first_name != nil || @user.last_name != nil %>
              <div class="input-group info-user mb-3">
                <span class="input-group-text"><i class="fa fa-user" aria-hidden="true"></i></span>
                <span class="user-email ml-2"><h6 class="info-user-text"><%= @user.first_name %> <%= @user.last_name %></h6></span>
              </div>
            <% end %>
            <div class="input-group info-user mb-3">
              <span class="input-group-text info-user"><i class="fa fa-envelope" aria-hidden="true" ></i></span>
              <span class="user-email ml-2"><h6 class="info-user-text"><%= @user.email%></h6></span>
            </div>
            <% if @user.address != nil || @user.city != nil || @user.country != nil %>
              <div class="input-group info-user mb-3">
                <span class="input-group-text info-user"><i class="fa fa-map-marker" aria-hidden="true" ></i></span>
                <span class="user-email ml-2">
                  <h6 class="info-user-text">
                    <% if @user.address.present?  %>
                      <%= @user.address %>, 
                    <% end %>
                    <% if @user.city.present? %>
                      <%= @user.city %>,
                    <% end %>
                    <% if @user.country.present? %>
                      <%= @user.country %>
                    <% end %>
                  </h6>
                </span>
              </div>
            <% end %>
            <div class="actions my-3">
              <%= link_to "Éditer mon profil", edit_users_path, "data-turbolinks" => "false", class:"btn btn-primary" %>
              <%= link_to "Éditer mon log in", edit_user_registration_path, class:"btn btn-outline-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr />
  <div class="mt-5 text-center col shadow p-3 mb-5 bg-white rounded my-pets">
    <h2 class="mt-3">Mes <span class="animal-friend">Amimaux</span></h2>
    <% if @user.pets.count != 0 %>
      <div class="row mt-5 d-flex justify-content-center" >
        <% @user.pets.each do |pet| %>
          <div class='col-3 col-user-animal'>
            <div id="likeCard<%= pet.id %>" class="card bg-light mb-3">
              <div id="likeHeader<%= pet.id %>" class="card-header">
                <h5 class="card-title-profile float-left"><%= pet.name%></h5>
                <h5>
                  <div class='float-right'>
                    <%if pet.id == @user.default_pet_id%>  
                      <i class="fa fa-star" aria-hidden="true" style="color:#f3c316"></i>
                    <%end%>
                  </div>
                </h5>
              </div>
              <div id="likeBody<%= pet.id %>" class="card-body">
                <% unless pet.photos.empty? %>
                  <%= image_tag pet.photos.first, class: "avatar-pet avatar-xlg mb-3 rounded-circle" %>
                <% else %>
                  <%= image_tag "michat.jpg", class: "avatar-pet avatar-xlg mb-3 rounded-circle"  %>
                <%end%>
                <div class="mt-3">
                  <div class="buttons-user-pets">
                    <div class="text-center button-user-pet">
                      <%=link_to "Voir son profil", pet_path(pet), class:'btn btn-sm btn-warning' %>
                    </div>
                    <div class="button-user-pet">
                      <%= form_for(current_user, url: users_path, method: :put) do |f| %>
                        <%= f.hidden_field :default_pet_id, :value => pet.id %>
                        <%= f.submit "Animal en vedette",class:"btn btn-sm btn-secondary mb-2" %>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    <% else %>
      <p class="mt-3">Vous n'avez aucun profil d'animal enregistré.</p>
    <% end %>
    <div class="col text-center">
      <div class="actions my-3 mt-4">          
        <%= link_to "Créer un animal", new_pet_path, "data-turbolinks" => "false", class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>