config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get '/whispaw', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  devise_for :users, path: "mon_compte"
  resource :users, :except => [:new, :create, :index, :destroy], path: "mon_profil"
  resources :tags, :except => [:edit, :update]
  resources :pets, path: "animaux" do
    resources :likes
    member do
      delete :delete_photo
    end
  end

  resources :messages
  resources :chatrooms, only: [:new, :create, :show, :index], path: "mes_conversations"
  mount ActionCable.server => '/cable'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="p-3 mt-5 d-flex justify-content-around" id="footer">
  <div class="container row">
    <div class="text-center col-md-4">
      <p class="text-light">© 2020 Copyright :</p>
      <p><%=link_to "Session # 12 The Hacking Project", "https://www.thehackingproject.org/", class:"text-light" %></p>
    </div>
    <div class="text-center col-md-3">
      <p><%= link_to "À propos de Whispaw ®", whispaw_path, class:"text-light" %></p>
      <p><%= link_to "Nous contacter", contact_path, class:"text-light" %></p>
    </div>
    <div class="text-center col-md-4">
      <p class="d-flex justify-content-around"><%= link_to "S'inscrire", new_user_registration_path, class:"btn btn-outline-light"  %>
        <%= link_to "Se connecter", new_user_session_path, class:"btn btn-outline-light" %>
      </p>
      <p>
        <%=link_to "https://www.instagram.com/whispawmatch/", class:"mx-3 h4 text-light footer-icon" do %>
          <i class="fa fa-instagram fa-1x footer-icon"></i>
          <span class="sr-only">Follow us on Instagram</span>
        <%end%>
        <%=link_to "https://www.facebook.com/whispawmatch/", class:"mx-3 h4 text-light footer-icon" do %>
          <i class="fa fa-facebook fa-1x footer-icon"></i>
          <span class="sr-only">Follow us on Facebook<span>
        <%end%>
        <%=link_to "https://github.com/agnesarth/Animal-matching", class:"mx-3 h4 text-light footer-icon" do %>
          <i class="fa fa-github fa-1x footer-icon"></i>
          <span class="sr-only">Follow us on GitHub<span>
        <%end%>
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <%= link_to root_path, class:"navbar-brand mr-2 ml-1" do %>
      <i class="fa fa-paw"></i> Whispaw
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Mon espace</a>
          <div class="dropdown-menu">
            <%= link_to "Mon profil", users_path, class:"dropdown-item" %>
            <%= link_to "Paramètres", edit_users_path, "data-turbolinks" => "false", class:"dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Animaux</a>
          <div class="dropdown-menu">
            <% if user_signed_in? && !current_user.default_pet_id.nil? %>
              <%= link_to "Rechercher des <i>amimaux</i>".html_safe, pets_path, "data-turbolinks" => "false", class:"dropdown-item" %>
              <%= link_to "Mes likes / mes matches", pet_likes_path(current_user.default_pet_id), class:"dropdown-item" %>
            <% else %>
              <%= link_to "Créer un animal", new_pet_path, class:"dropdown-item" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Tags", tags_path, "data-turbolinks" => "false", class:"nav-link" %>
        </li>
        <% if current_user.default_pet_id && any_match? %>
        <li class="nav-item">
          <%= link_to "Contacter mes matchs", chatrooms_path, class:"nav-link" %>
        </li>
       <%end%>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if !current_user.default_pet_id.nil? %>
          <li class="nav-item">
            <em><%= link_to "#{Pet.find(current_user.default_pet_id).name.capitalize} en ligne", users_path, :class => "nav-link" %></em>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Se déconnecter", destroy_user_session_path, {:method => :delete, :class => "nav-link"} %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag(source = "paw.jpg", options = {}) %>
    <title>Whispaw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track": true %>
  </head>
  <body>
    <div id="content-wrap">
      <%= render 'layouts/navbar'%>
      <%= render 'layouts/flash'%>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>